### ISSUE TITLE
Integration not working with HA Core 2023.5

### ISSUE THREAD

**Issue by aturri** [aturri/ha-zcsazzurro#7]
### The problem

Integration reports all sensors unavailable after upgrading to Homeassistant Core 2023.5

### Version of zcsazzurro integration having the issue?

0.0.5

### Version of Home Assistant Core having the issue?

2023.5

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/zcsazzurro/__init__.py", line 109, in async_fetch
    result = await zcs_portal.fetch_real_time_data()
  File "/config/custom_components/zcsazzurro/api.py", line 44, in fetch_real_time_data
    result = await self._fetch_data(payload)
  File "/config/custom_components/zcsazzurro/api.py", line 64, in _fetch_data
    rest = RestData(
  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 47, in __init__
    self._ssl_cipher_list = SSLCipherList(ssl_cipher_list)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 30 is not a valid SSLCipherList
```

**Comment by aturri** [comment]
Related to https://github.com/home-assistant/core/pull/91078

**Comment by aturri** [comment]
Fixed by https://github.com/aturri/ha-zcsazzurro/releases/tag/v0.0.6
